# Permalinks
permalink:        /:categories/:year/:month/:day/:title

# Setup
title:            "I'm Su Ho V."
url:              https://suho.github.io
baseurl:          '/'
description:      'Engineer'

excerpt_separator: '<!--excerpt-->'

author:
  name:           'Su Ho V.'
  url:            https://github.com/suho

paginate:         5

# Custom vars
version:          1.0.0
username:         'mlsuho'
twitter:          https://twitter.com/twsuho
github:
  base:           https://github.com/suho
  repo:           https://github.com/suho/suho.github.io
linkedin:         https://www.linkedin.com/in/suho

plugins:
  - jekyll-paginate
  - jekyll-gist
