# Permalinks
permalink:        /:categories/:title

# Setup
title:            'Su Ho V.'
url:              https://mlsuho.github.io
baseurl:          '/'
description:      'Engineer'

excerpt_separator: '<!--excerpt-->'

author:
  name:           'Su Ho V.'
  url:            https://github.com/mlsuho

paginate:         5

# Custom vars
version:          1.0.0
username:         'mlsuho'
twitter:          https://twitter.com/mlsuho
github:
  base:           https://github.com/mlsuho
  repo:           https://github.com/mlsuho/mlsuho.github.io
linkedin:         https://www.linkedin.com/in/mlsuho

plugins:
  - jekyll-paginate
  - jekyll-gist